---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}"
spec:
  vmProberSpec:
    url: tech-prometheus-blackbox-exporter.tech.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      targets:
        - http://{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}.apps.svc.cluster.local
  interval: "30s"
  scrapeTimeout: "30s"


# ---
# apiVersion: operator.victoriametrics.com/v1beta1
# kind: VMPodScrape
# metadata:
#   name: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}"
# spec:
#   selector:
#     matchLabels:
#       service: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}"
#   podMetricsEndpoints:
#     - port: "http"
#       scheme: "http"
#       interval: "15s"
#       scrapeTimeout: "10s"
#       bearerTokenSecret:
#         name: prometheus-auth
#         key: key
#       relabelConfigs:
#         - action: labelmap
#           regex: __meta_kubernetes_pod_label_(.+)
