---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}-retry"
  namespace: "apps"
spec:
  retry:
    attempts: 10
    initialInterval: 100ms

{{ if eq .Values.branch "master" }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}"
  namespace: "apps"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tiksat.bid`)
      middlewares:
        - name: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}-retry"
      kind: Rule
      services:
        - name: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}"
          port: 80
  tls:
    domains:
      - main: tiksat.bid
    secretName: traefik-cloudflare-cert
{{ else }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}"
  namespace: "apps"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $.Values.branch }}.{{ $.Values.domain }}`)
      middlewares:
        - name: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}-retry"
      kind: Rule
      services:
        - name: "{{ $.Values.appType }}-{{ include "apps-frontend.branch" . }}"
          port: 80
  tls:
    certResolver: main-le
{{ end }}
